### ISSUE TITLE
Permission denied error on vis.py file 

### ISSUE THREAD

**Issue by vsumm** [seominseok0429/Real-world-Anomaly-Detection-in-Surveillance-Videos-pytorch#24]
i am working on latest and updated code given in zip file 

train script works very and I trying to run vis.py file I got below error 

```
Traceback (most recent call last):                                                                        
File "C:\Users\Fraction Analytics\Downloads\Real-world-Anomaly-Detection-in-Surveillance-Videos-pytorch\VIS\vis.py", line 135, in <module>                     
                      
 inputs[:,:,num,:,:] = ToTensor(1)(Image.open(i))        
                                     
File "C:\Users\Fraction Analytics\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 3236, in open                                                          fp = builtins.open(filename, "rb")                                                         

PermissionError: [Errno 13] Permission denied: '/$Recycle.Bin'  

'''

how to resolve this issue 

thanks @seominseok0429

**Comment by Jeon21** [comment]
Did you solve this problem?

**Comment by tuananh5701b** [comment]
same my problem. Have you solved it yet? If you solved it, can you help me.

**Comment by ajuhbw** [comment]
> same my problem. Have you solved it yet? If you solved it, can you help me.

> same my problem. Have you solved it yet? If you solved it, can you help me.

Do the following:

`vis.py
parser.add_argument('--n', default='./Abuse001_x264', type=str, help='file name')`

This is line 34 of vis.py.
In this way, set the path of the folder where the frame image is located.
