### ISSUE TITLE
vis.py 관련 질문입니다

### ISSUE THREAD

**Issue by Jeon21** [seominseok0429/Real-world-Anomaly-Detection-in-Surveillance-Videos-pytorch#25]
안녕하세요 vis.py 코드를 실행중 생긴 오류인데 혹시 해결방법 아시나요...? 
제가 $Recycle.Bin 권한도 수정했는데 고쳐지질않네요ㅠㅠ 
운영체제는 윈도우 10이고 
GPU = RTX3070
python = 3.8.17
torch = 1.8.0+cu111
torchvision =  0.9.0+cu111
pillow = 10.0.0
입니다. 

>(MGFN) D:\pleaseplease>C:/Users/user/anaconda3/envs/MGFN/python.exe d:/pleaseplease/VIS/vis.py
Traceback (most recent call last):
  File "d:/pleaseplease/VIS/vis.py", line 135, in <module>
    inputs[:,:,num,:,:] = ToTensor(1)(Image.open(i))
  File "C:\Users\user\anaconda3\envs\MGFN\lib\site-packages\PIL\Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
PermissionError: [Errno 13] Permission denied: '/$RECYCLE.BIN'

**Comment by tuananh5701b** [comment]
same my problem. Have you solved it yet? If you solved it, can you help me.
